version: '3'
networks:
  production:
services:
  postgres:
    image: postgres:13.5-alpine
    # This needs to run as root for migrations to succeed
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        -  ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - production
  redis:
    image: redis:4.0-alpine
    command: redis-server
    restart: on-failure
    networks:
      - production
    volumes:
      -  ${APP_DATA_DIR}/data/redis:/var/shared/redis
  worker:
    image: dakhodl/peacemaker:v0.3.1
    volumes:
      - production_hidden_service:/var/app/hidden_service
    networks:
      - production
    stdin_open: true
    restart: on-failure
    tty: true
    command: ["bundle", "exec", "sidekiq"]
    environment:
      RAILS_ENV: production
      REDIS_URL_SIDEKIQ: "redis://redis:6379/1"
      SOCKS_PROXY_URL: "production_web"
    depends_on:
      - redis
      - web
  web:
    image: dakhodl/peacemaker:v0.3.1
    volumes:
      -  ${APP_DATA_DIR}/data/hidden_service:/var/app/hidden_service
    networks:
      - production
    ports:
      - 7777:3000
    stdin_open: true
    restart: on-failure
    tty: true
    entrypoint: production-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: production
      REDIS_URL_SIDEKIQ: "redis://redis:6379/1"
      WEB_PASSWORD: 'changeme'
      WEB_USERNAME: 'admin'
    depends_on:
      - redis
      - postgres
